CREATE TABLE codificacion.cod_p32esp_temp3 (
	id_p32esp serial4 NOT NULL,
	secuencial int4 DEFAULT 0 NULL,
	id_vivienda int8 NOT NULL,
	id_persona int8 NOT NULL,
	nro_32 varchar(8) NULL,
	i00 varchar(8) NULL,
	i001a varchar(8) NULL,
	nro int4 NULL,
	respuesta text NULL,
	codigocodif varchar(30) NULL,
	codigocodif_v1 varchar(30) NULL,
	codigocodif_v2 varchar(30) NULL,
	"estado" varchar(60) DEFAULT 'ELABORADO'::character varying NOT NULL,
	usucre varchar(60) NULL,
	feccre timestamp(6) DEFAULT now() NOT NULL,
	usucodificador varchar(60) NULL,
	feccodificador timestamp(6) NULL,
	usuverificador varchar(60) NULL,
	fecverificador timestamp(6) NULL,
	usuverificador2 varchar(60) NULL,
	fecverificador2 timestamp(6) NULL,
	respuesta_normalizada text DEFAULT 'Sin Observaciones'::text NULL,
	departamento varchar(20) NULL,
	orden int4 DEFAULT 0 NULL,
	estado_norm int4 DEFAULT 0 NULL,
	carga int4 NULL,
	i001a_copia varchar(8) NULL,
	segmento varchar(8) NULL,
	verificado int4 DEFAULT 0 NULL,
	id_codificacion int4 NULL,
	cod_depto varchar(2) NULL,
	CONSTRAINT cod_p32esp_temp3_pkey PRIMARY KEY (id_p32esp),
	CONSTRAINT cod_p32esp_temp3_secuencial_i00_i001a_nro_key UNIQUE (id_persona, i00, i001a, nro)
);

